#cloud-config
users:
  - name: username
    ssh-authorized-keys:
      - ssh-rsa KEY
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo, docker
    shell: /bin/bash
runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers username' /etc/ssh/sshd_config
  - ufw allow OpenSSH
  - ufw allow http
  - ufw allow https
  - ufw enable
  - restart ssh
