version: '3.1'

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:1.7
    command: --docker
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:***REMOVED***
      - traefik.port=8080
    container_name: traefik
