version: '3.1'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: supersecret

  ghost:
    ports:
      - 80:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: blog_user
      database__connection__password: supersecret
      database__connection__database: db
