version: '3.1'

services:
  ghost:
    environment:
      storage__active: s3
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET: $GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      AWS_SIGNATURE_VERSION: $AWS_SIGNATURE_VERSION
