version: '3.1'

volumes:
  db-volume:
  ghost-volume:

networks:
  proxy:
    external:
      name: traefik_default
  backend:

services:
  db:
    image: mariadb:10.3.9
    restart: unless-stopped
    container_name: db
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

  ghost:
    build: ./build
    image: lmcly/ghost:2.0.3
    container_name: ghost
    volumes:
      - ghost-volume:/var/lib/ghost/content
    restart: unless-stopped
    networks:
      - proxy
      - backend
    ports:
      - 2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: $MYSQL_USER
      database__connection__password: $MYSQL_PASSWORD
      database__connection__database: $MYSQL_DATABASE
      url: https://$GHOST_DOMAIN
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.frontend.rule=Host:$GHOST_DOMAIN
      - traefik.port=2368
    entrypoint: ["wait-for-it.sh", "db", "--", "docker-entrypoint.sh"]
    command: ["node", "current/index.js"]
